version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
    - "${fastapi_port}:${fastapi_port}"
    volumes:
    - .:/app
    env_file:
      - .env

    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: